from lexer import Lexer
from parser import Parser
from my_ast import print_ast


def main():
    # Input arithmetic expression with new operators and parentheses
    text = "(12 + 3) * 4 - 6 / (2 + 1)"

    # Create a lexer and tokenize the input text
    lexer = Lexer(text)
    lexer.tokenize()

    # Create a parser and parse the tokens into an AST
    parser = Parser(lexer)
    ast = parser.parse()

    # Print tokens generated by lexer
    print("Tokens:")
    for token in lexer.tokens:
        print(token)

    # Print AST generated by parser
    print("\nAST:")
    print_ast(ast)


if __name__ == "__main__":
    main()
